// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCYA5uZW5dM72jQHs5OlX4RK7OjgtIKgc',
    appId: '1:242633284233:web:383a921d3f566634178458',
    messagingSenderId: '242633284233',
    projectId: 'grievanceapp-f2446',
    authDomain: 'grievanceapp-f2446.firebaseapp.com',
    storageBucket: 'grievanceapp-f2446.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMRy6B8f_9bLEIxhsGWTGmywLwtNiLGk8',
    appId: '1:242633284233:android:83ca7125caf5be00178458',
    messagingSenderId: '242633284233',
    projectId: 'grievanceapp-f2446',
    storageBucket: 'grievanceapp-f2446.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe8wSLMn2dXaNirms2wQSS6jxNusYH9Nc',
    appId: '1:242633284233:ios:4896d875434ad3bd178458',
    messagingSenderId: '242633284233',
    projectId: 'grievanceapp-f2446',
    storageBucket: 'grievanceapp-f2446.appspot.com',
    iosBundleId: 'com.example.loginagain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe8wSLMn2dXaNirms2wQSS6jxNusYH9Nc',
    appId: '1:242633284233:ios:2eb344c83e2a7b15178458',
    messagingSenderId: '242633284233',
    projectId: 'grievanceapp-f2446',
    storageBucket: 'grievanceapp-f2446.appspot.com',
    iosBundleId: 'com.example.loginagain.RunnerTests',
  );
}
